### ISSUE TITLE
Null alignment file

### ISSUE THREAD

**Issue by JuliaLopezDelgado** [shingocat/agisps#29]
I am trying to run LRScaf with the following commands:
> minimap2 -ax map-ont -t 8 assembly.fasta ONT.fasta > align.mm
java -Xms200g -Xmx200g -jar LRScaf-1.1.10.jar -c assembly.fasta -a align.mm -t mm -o out

I am getting the following error:
> 2021-05-12 15:54:44  [ ERROR ]  Error: 
org.apache.commons.cli.MissingArgumentException: The type of aligned file could not be null!
	at agis.ps.Main.parsering(Main.java:180)
	at agis.ps.Main.main(Main.java:53)
2021-05-12 15:54:44  [ ERROR ]  agis.ps.Main	The type of aligned file could not be null!
2021-05-12 15:57:45  [ ERROR ]  agis.ps.file.MMReader	On lines: 1	For input string: "SN:contig_1"
2021-05-12 15:57:45  [ ERROR ]  PathBuilder ï¼š The Edges could not be empty!
2021-05-12 16:00:23  [ ERROR ]  agis.ps.file.M4Reader	On lines: 1	3
2021-05-12 16:00:23  [ ERROR ]  PathBuilder ï¼š The Edges could not be empty!
2021-05-12 16:02:45  [ ERROR ]  PathBuilder ï¼š The Edges could not be empty!

Could you please help me with this error? 

Thanks in advance!
Julia

**Comment by shingocat** [comment]
Julia,

On your minimap2 alignment command, using "-a" is to output in sam format nor PAF format which it is the type mm format on LRScaf.
