### ISSUE TITLE
might be inconsistent log messages?

### ISSUE THREAD

**Issue by Gjocund** [shingocat/agisps#34]
Hi~

I have tried to run LRScaf using nanopore long reads and an assembly file, and with default parameters in ScafConf.xml.
java -jar ~/lrscaf-master/target/LRScaf-1.1.12.jar -x ScafConf.xml
The messages I got are similar to this post, https://github.com/shingocat/lrscaf/issues/13:

$ cat logs/error.log
2021-08-26 22:40:34  [ ERROR ]  Error:
org.apache.commons.cli.MissingArgumentException: The aligned file could not be null!
        at agis.ps.Main.parsering(Main.java:161)
        at agis.ps.Main.main(Main.java:48)
2021-08-26 22:40:34  [ ERROR ]  agis.ps.Main    The aligned file could not be null!

$ cat logs/logs.log
2021-08-26 22:42:23  [ INFO ]  Parsing the xml configure, all the other parameters set by command line will dismissed!
2021-08-26 22:42:24  [ INFO ]  Launching...
2021-08-26 22:42:24  [ INFO ]  Build output folder successfully!
2021-08-26 22:42:24  [ INFO ]  Building output folder, elapsed time: 2 ms
2021-08-26 22:43:14  [ INFO ]  Reading contigs, elapsed times: 49913 ms
2021-08-26 22:47:51  [ INFO ]  Valid Aligned Records: 756966
2021-08-26 22:47:51  [ INFO ]  Reading Aligned Records, elapsed time: 277126 ms
2021-08-26 22:47:52  [ INFO ]  Finding Repeats:
2021-08-26 22:47:52  [ INFO ]  MIN: 1.0
2021-08-26 22:47:52  [ INFO ]  First Quartile: 4.0
2021-08-26 22:47:52  [ INFO ]  Median cov = 12.0
2021-08-26 22:47:52  [ INFO ]  Third Quartile: 17.0
2021-08-26 22:47:52  [ INFO ]  MAX: 41645.0
2021-08-26 22:47:52  [ INFO ]  Interquartile Range: 13.0
2021-08-26 22:47:52  [ INFO ]  1.5's IQR , Outlier Threshold: 36.5
2021-08-26 22:47:52  [ INFO ]  Repeat count: 31624
2021-08-26 22:47:52  [ INFO ]  Finding repeat, elapsed time: 528 ms
…

Because the error.log said: "**Error: The aligned file could not be null!**", but the logs.log says, "**Valid Aligned Records: 756966**", I think these two logs are easy to make first time users confused about how the program is running.
I wish the log files could report the **real** situation (whether the software is doing well), thank you.

**Comment by LGliuliuliu** [comment]
Hi,-m 4 format alignment how did you get it
