### ISSUE TITLE
Troubleshooting errors

### ISSUE THREAD

**Issue by 000generic** [shingocat/agisps#7]
Hi!

I'm making a first pass at using LRScaf and having trouble making sense of the failed output. LRScaf exit status was 0 but I'm not seeing a hybrid assembly - and like others here - but maybe not identical - I am also getting the edges could not be empty error - and an error in the MMReader input string. 

I have a very poor Discovar assembly for the pygmy octopus genome (over 6 million scaffolds) and a first pass of MinION reads (150,000 reads).  The genome is around human size - and I estimate MinION coverage is about 0.68x - Illumina coverage is around 80x going into the Discovar assembly but the assembly did not turn out well.  I used minimap2 with default settings.  

**logs/error.log from LRScaf:**

2019-01-12 15:50:26  [ main:466447 ] - [agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:163)] - **[ ERROR ]  agis.ps.file.MMReader For input string: "collected"**
2019-01-12 15:50:26  [ main:466475 ] - [agis.ps.Scaffolder.scaffolding(Scaffolder.java:82)] - ### **[ ERROR ]  PathBuilder ： The Edges could not be empty!**

**logs/logs.log from LRScaf:**

2019-01-12 15:42:40  [ main:0 ] - [agis.ps.Main.main(Main.java:48)] - [ INFO ]  Parsing the xml configure, all the other parameters set by command line will dismissed
2019-01-12 15:42:40  [ main:58 ] - [agis.ps.file.XMLParser.parseXML(XMLParser.java:182)] - **[ INFO ]  agis.ps.file.XMLParser     The para element contain illeage item tips_length. it will be omitted!**
2019-01-12 15:42:40  [ main:59 ] - [agis.ps.Main.main(Main.java:56)] - [ INFO ]  Launching...
2019-01-12 15:42:40  [ main:70 ] - [agis.ps.file.OutputFolderBuilder.building(OutputFolderBuilder.java:42)] - [ INFO ]  Build output folder successfully!
2019-01-12 15:42:40  [ main:71 ] - [agis.ps.file.OutputFolderBuilder.building(OutputFolderBuilder.java:52)] - [ INFO ]  Building output folder, erase time: 8 ms
2019-01-12 15:50:24  [ main:464505 ] - [agis.ps.file.ContigReader.read(ContigReader.java:149)] - [ INFO ]  Reading contigs, erase times: 464429 ms
2019-01-12 15:50:26  [ main:466447 ] - [agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:163)] - **[ ERROR ]  agis.ps.file.MMReader For input string: "collected"**
2019-01-12 15:50:26  [ main:466450 ] - [agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:176)] - **[ INFO ]  Valid Aligned Records: 0**
2019-01-12 15:50:26  [ main:466450 ] - [agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:177)] - [ INFO ]  Reading Aligned Records, erase time: 19 ms
2019-01-12 15:50:26  [ main:466451 ] - [agis.ps.util.RepeatFinder.findRepeats(RepeatFinder.java:123)] - **[ INFO ]  Repeat count: 0**
2019-01-12 15:50:26  [ main:466451 ] - [agis.ps.util.RepeatFinder.findRepeats(RepeatFinder.java:125)] - [ INFO ]  Finding repeat, erase time: 0 ms
2019-01-12 15:50:26  [ main:466453 ] - [agis.ps.util.LinkBuilder.mRecords2Links(LinkBuilder.java:93)] - [ INFO ]  Valid Links Acount: 0
2019-01-12 15:50:26  [ main:466453 ] - [agis.ps.util.LinkBuilder.mRecords2Links(LinkBuilder.java:94)] - [ INFO ]  Building Link, erase time : 0 ms
2019-01-12 15:50:26  [ main:466475 ] - [agis.ps.Scaffolder.scaffolding(Scaffolder.java:82)] - **[ ERROR ]  PathBuilder ： The Edges could not be empty!**
2019-01-12 15:50:26  [ main:466476 ] - [agis.ps.Main.main(Main.java:59)] - [ INFO ]  Ending...
2019-01-12 15:50:26  [ main:466476 ] - [agis.ps.Main.main(Main.java:61)] - [ INFO ]  Scaffolding erase time: 466 s.

**files in the output folder are largely empty:**

[eedsinger@barhal minimap2-ee20190111-1]$ ls -1la 5-lrscaff-output/
total 15
drwxr-xr-x 2 eedsinger eedsinger   5 Jan 12 15:50 .
drwxrwxr-x 4 eedsinger eedsinger  14 Jan 12 15:50 ..
-rw-r--r-- 1 eedsinger eedsinger 189 Jan 12 15:50 draft_summary.info
-rw-r--r-- 1 eedsinger eedsinger   **0** Jan 12 15:50 links.info
-rw-r--r-- 1 eedsinger eedsinger   **0** Jan 12 15:50 triadlinks.info

**configure.xml given to LRScaf:**
See attached.

**Any suggestions would be greatly appreciated!**

Thank-you very much,
Eric
[configure.txt](https://github.com/shingocat/lrscaf/files/2752568/configure.txt)

**Comment by shingocat** [comment]
Hi Eric,

Could you offer some rows of your PAF file? Since LRScaf could not build links information from your PAF file, the outcome would be empty.

**Comment by AndreaGuarracino** [comment]
Hi, @shingocat, may I ask help? I have the same problem.

```
2020-04-15 23:57:01 [ ERROR ]  agis.ps.file.MMReader	For input string: "0,4967"
2020-04-15 23:57:01 [ INFO ]  Valid Aligned Records: 0
```

The first lines of the PAF file are the following:

```
LongReads_1	7076	136	6701	+	754	10397	32	6857	3425	6895	60	tp:A:P	cm:i:424	s1:i:3367	s2:i:104	dv:f:0.0718	rl:i:0
LongReads_1	7076	6744	6972	+	7316	1680	1418	1656	97	240	9	tp:A:P	cm:i:7	s1:i:95	s2:i:88	dv:f:0.1195	rl:i:0
LongReads_1	7076	6711	6972	+	4888	864	589	860	90	273	0	tp:A:S	cm:i:6	s1:i:88	dv:f:0.1358	rl:i:0
LongReads_1	7076	6711	6819	+	10020	1648	1529	1634	60	109	0	tp:A:S	cm:i:4	s1:i:60	dv:f:0.1003	rl:i:0
LongReads_1	7076	6711	6780	+	8986	1029	908	976	45	70	5	tp:A:P	cm:i:3	s1:i:45	s2:i:0	dv:f:0.0978	rl:i:0
LongReads_2	9896	114	8527	+	754	10397	4	8573	4770	8682	60	tp:A:P	cm:i:599	s1:i:4731	s2:i:107	dv:f:0.0644	rl:i:247
LongReads_2	9896	8558	9805	+	7316	1680	376	1674	516	1310	45	tp:A:P	cm:i:67	s1:i:505	s2:i:408	dv:f:0.0802	rl:i:247
LongReads_2	9896	8558	9646	+	10020	1648	510	1634	418	1136	0	tp:A:S	cm:i:52	s1:i:408	dv:f:0.0867	rl:i:247
LongReads_3	6823	102	6382	+	754	10397	4	6380	2756	6506	60	tp:A:P	cm:i:332	s1:i:2709	s2:i:70	dv:f:0.0860	rl:i:0
LongReads_3	6823	6488	6747	+	7316	1680	1389	1674	110	285	56	tp:A:P	cm:i:13	s1:i:105	s2:i:73	dv:f:0.0842	rl:i:0
```

**Comment by pdroslva84** [comment]
Hi @shingocat , I'm having the exact same problem as @AndreaGuarracino :

> 2020-04-16 15:22:58 [ ERROR ]  agis.ps.file.MMReader	For input string: "0,4909"
> 2020-04-16 15:22:58 [ INFO ]  Valid Aligned Records: 0

I have no idea where the string "0,4909" is supposed to come from.

My alignment file from minimap has ca. 1.4M lines, here's the first 10:

```
9818ac31-88fb-4fc5-954b-94ad4bd23982	1285	120	741	+	tig00003288_pilon	4453	1766	2422	322	656	60	tp:A:P	cm:i:39	s1:i:315	s2:i:0	dv:f:0.0721	rl:i:0
65d79b66-1311-428d-883a-03e35ac86553	1652	79	1103	+	tig00146187_pilon	22466	13260	14310	478	1075	60	tp:A:P	cm:i:62	s1:i:468	s2:i:185	dv:f:0.0764rl:i:15
65d79b66-1311-428d-883a-03e35ac86553	1652	1188	1555	-	tig00146187_pilon	22466	13280	13687	174	416	60	tp:A:P	cm:i:21	s1:i:164	s2:i:0	dv:f:0.0783	rl:i:15
18c120d5-b8cc-412d-b06b-a8c118641c58	676	179	360	-	tig00044843_pilon	25809	6978	7162	128	186	0	tp:A:P	cm:i:19	s1:i:127	s2:i:127	dv:f:0.0462rl:i:0
18c120d5-b8cc-412d-b06b-a8c118641c58	676	179	360	+	tig00044843_pilon	25809	10499	10684	128	187	0	tp:A:S	cm:i:19	s1:i:127	dv:f:0.0462	rl:i:0
ebc4dc98-5be3-4af3-a40e-252b6084a5b3	1314	89	726	-	tig00147134_pilon	9295	6078	6718	452	650	0	tp:A:P	cm:i:61	s1:i:449	s2:i:449	dv:f:0.0428rl:i:15
ebc4dc98-5be3-4af3-a40e-252b6084a5b3	1314	89	726	-	tig00146817_pilon	15922	3206	3846	452	650	0	tp:A:S	cm:i:61	s1:i:449	dv:f:0.0428	rl:i:15
ebc4dc98-5be3-4af3-a40e-252b6084a5b3	1314	93	726	+	tig00146817_pilon	15922	15248	15874	417	646	0	tp:A:S	cm:i:54	s1:i:412	dv:f:0.0504	rl:i:15
ece88195-ec12-4290-a9ce-313fb4186a3c	5257	622	2255	-	tig00147155_pilon	3208	1255	2980	171	1740	16	tp:A:P	cm:i:16	s1:i:149	s2:i:137	dv:f:0.1982rl:i:0
ece88195-ec12-4290-a9ce-313fb4186a3c	5257	622	2255	+	tig00147156_pilon	2620	241	1960	159	1736	0	tp:A:S	cm:i:14	s1:i:137	dv:f:0.2071	rl:i:0
```

**Comment by shingocat** [comment]
Hi AndreaGuarracino and pdroslva84, 
I have test the lines you paste. 
It work fine.
Maybe there are some lines in your PAF file not right?
I have add a debug to show which  line is not correct. 
And I have uploaded the LRScaf-1.1.8r1.jar on https://github.com/shingocat/lrscaf/tree/master/target.
you can download this, run again and feedback me what is the content of the exception line.
Thanks.

The output looks like 2020-04-17 17:11:34 [ ERROR ]  agis.ps.file.MMReader	On lines: 1	For input string: "424c"
2020-04-17 17:11:34 [ INFO ]  Valid Aligned Records: 0
2020-04-17 17:11:34 [ INFO ]  Reading Aligned Records, erase time: 7 ms

**Comment by AndreaGuarracino** [comment]
Thank you @shingocat. This is the output:

```
2020-04-17 12:55:02 [ ERROR ]  agis.ps.file.MMReader	On lines: 1	For input string: "0,4967"
2020-04-17 12:55:02 [ INFO ]  Valid Aligned Records: 0
2020-04-17 12:55:02 [ INFO ]  Reading Aligned Records, erase time: 4 ms
2020-04-17 12:55:02 [ INFO ]  Repeat count: 0
2020-04-17 12:55:02 [ INFO ]  Finding repeat, erase time: 0 ms
2020-04-17 12:55:02 [ INFO ]  Valid Links Acount: 0
2020-04-17 12:55:02 [ INFO ]  Building Link, erase time : 10 ms
```

**Comment by pdroslva84** [comment]
Hi @shingocat 

this is the output of the debug jar:

```
2020-04-17 12:58:08 [ WARN ]  The identity for minimap mapper would be setted to 0.1!
2020-04-17 12:58:08 [ INFO ]  Launching...
2020-04-17 12:58:08 [ INFO ]  The output folder existed!
2020-04-17 12:58:08 [ INFO ]  Building output folder, erase time: 0 ms
2020-04-17 12:58:08 [ INFO ]  Reading contigs, erase times: 553 ms
2020-04-17 12:58:08 [ ERROR ]  agis.ps.file.MMReader	On lines: 1	For input string: "0,4909"
2020-04-17 12:58:08 [ INFO ]  Valid Aligned Records: 0
2020-04-17 12:58:08 [ INFO ]  Reading Aligned Records, erase time: 7 ms
2020-04-17 12:58:08 [ INFO ]  Repeat count: 0
2020-04-17 12:58:08 [ INFO ]  Finding repeat, erase time: 0 ms
2020-04-17 12:58:08 [ INFO ]  Valid Links Acount: 0
2020-04-17 12:58:08 [ INFO ]  Building Link, erase time : 5 ms
2020-04-17 12:58:08 [ ERROR ]  PathBuilder ： The Edges could not be empty!
2020-04-17 12:58:08 [ INFO ]  Ending...
2020-04-17 12:58:08 [ INFO ]  Scaffolding erase time: 0 s.
```

For me the same error also appears if I run it on the first 10 lines that I pasted above.

**Comment by shingocat** [comment]
Hi pdroslva84,

I have upload a new debug version LRScaf-1.1.8r2.jar. 
Could you help me to run again and feedback to me?
Since the lines you pasted, it work fine (you could see the following output). 
And if I could locate where the exception throwed,  I will try to fix this as soon as possible. 
Thanks.

2020-04-18 11:37:30 [ WARN ]  The identity for Minimap mapper should be not large than 0.3!
2020-04-18 11:37:30 [ INFO ]  Launching...
2020-04-18 11:37:30 [ INFO ]  The output folder existed!
2020-04-18 11:37:30 [ INFO ]  Building output folder, erase time: 1 ms
2020-04-18 11:37:30 [ INFO ]  Reading contigs, erase times: 1 ms
2020-04-18 11:37:30 [ INFO ]  The output file D:\data\lrscaf\output\draft_summary.info existed. It will overwrite.
2020-04-18 11:37:30 [ DEBUG ]  MRecord [qName=9818ac31-88fb-4fc5-954b-94ad4bd23982, qLength=1285, qStart=120, qEnd=741, qStrand=null, tName=tig00003288_pilon, tLength=4453, tStart=1766, tEnd=2422, tStrand=+, identity=0.4909]
2020-04-18 11:37:30 [ DEBUG ]  MRecordValidator on lines 1 done.
2020-04-18 11:37:30 [ DEBUG ]  Repeat finding on lines 1 done.
2020-04-18 11:37:30 [ DEBUG ]  Record saving on lines 1 done.
2020-04-18 11:37:30 [ DEBUG ]  MRecord [qName=65d79b66-1311-428d-883a-03e35ac86553, qLength=1652, qStart=79, qEnd=1103, qStrand=null, tName=tig00146187_pilon, tLength=22466, tStart=13260, tEnd=14310, tStrand=+, identity=0.4447]
2020-04-18 11:37:30 [ DEBUG ]  MRecordValidator on lines 2 done.
2020-04-18 11:37:30 [ DEBUG ]  Repeat finding on lines 2 done.
2020-04-18 11:37:30 [ DEBUG ]  Record saving on lines 2 done.

**Comment by AndreaGuarracino** [comment]
Hi @shingocat,

I tried the last build using onlu the first line of my PAF. The problem is still there:

```
2020-04-18 09:20:17 [ INFO ]  Parsing the xml configure, all the other parameters set by command line will dismissed!
2020-04-18 09:20:17 [ WARN ]  The identity is setted to 0.3.
2020-04-18 09:20:17 [ WARN ]  The identity for Minimap mapper should be not large than 0.3!
2020-04-18 09:20:17 [ INFO ]  Launching...
2020-04-18 09:20:17 [ INFO ]  Build output folder successfully!
2020-04-18 09:20:17 [ INFO ]  Building output folder, erase time: 0 ms
2020-04-18 09:20:17 [ INFO ]  Reading contigs, erase times: 120 ms
2020-04-18 09:20:17 [ ERROR ]  agis.ps.file.MMReader	On lines: 1	java.lang.NumberFormatException: For input string: "0,4967"
2020-04-18 09:20:17 [ ERROR ]  agis.ps.file.MMReader	On lines: 1	For input string: "0,4967"
java.lang.NumberFormatException: For input string: "0,4967"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at agis.ps.file.MMReader.initMRecord(MMReader.java:37)
	at agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:107)
	at agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:59)
	at agis.ps.Scaffolder.buildLinks(Scaffolder.java:118)
	at agis.ps.Scaffolder.scaffolding(Scaffolder.java:74)
	at agis.ps.Main.main(Main.java:58)
2020-04-18 09:20:17 [ INFO ]  Valid Aligned Records: 0
2020-04-18 09:20:17 [ INFO ]  Reading Aligned Records, erase time: 3 ms
2020-04-18 09:20:17 [ INFO ]  Repeat count: 0
2020-04-18 09:20:17 [ INFO ]  Finding repeat, erase time: 0 ms
2020-04-18 09:20:17 [ INFO ]  Valid Links Acount: 0
2020-04-18 09:20:17 [ INFO ]  Building Link, erase time : 5 ms
java.lang.IllegalArgumentException: PathBuilder ： The Edges could not be empty!
	at agis.ps.util.PathBuilder.buildPath(PathBuilder.java:70)
	at agis.ps.Scaffolder.buildPaths(Scaffolder.java:144)
	at agis.ps.Scaffolder.scaffolding(Scaffolder.java:76)
	at agis.ps.Main.main(Main.java:58)
2020-04-18 09:20:17 [ ERROR ]  PathBuilder ： The Edges could not be empty!
2020-04-18 09:20:17 [ INFO ]  Ending...
2020-04-18 09:20:17 [ INFO ]  Scaffolding erase time: 0 s.
```

Here the PAF I've just used (**aln2.mm**):

```
LongReads_1	7076	136	6701	+	754	10397	32	6857	3425	6895	60	tp:A:P	cm:i:424	s1:i:3367	s2:i:104	dv:f:0.0718	rl:i:0
LongReads_1	7076	6744	6972	+	7316	1680	1418	1656	97	240	9	tp:A:P	cm:i:7	s1:i:95	s2:i:88	dv:f:0.1195	rl:i:0
LongReads_1	7076	6711	6972	+	4888	864	589	860	90	273	0	tp:A:S	cm:i:6	s1:i:88	dv:f:0.1358	rl:i:0
LongReads_1	7076	6711	6819	+	10020	1648	1529	1634	60	109	0	tp:A:S	cm:i:4	s1:i:60	dv:f:0.1003	rl:i:0
LongReads_1	7076	6711	6780	+	8986	1029	908	976	45	70	5	tp:A:P	cm:i:3	s1:i:45	s2:i:0	dv:f:0.0978	rl:i:0
LongReads_2	9896	114	8527	+	754	10397	4	8573	4770	8682	60	tp:A:P	cm:i:599	s1:i:4731	s2:i:107	dv:f:0.0644	rl:i:247
LongReads_2	9896	8558	9805	+	7316	1680	376	1674	516	1310	45	tp:A:P	cm:i:67	s1:i:505	s2:i:408	dv:f:0.0802	rl:i:247
LongReads_2	9896	8558	9646	+	10020	1648	510	1634	418	1136	0	tp:A:S	cm:i:52	s1:i:408	dv:f:0.0867	rl:i:247
LongReads_3	6823	102	6382	+	754	10397	4	6380	2756	6506	60	tp:A:P	cm:i:332	s1:i:2709	s2:i:70	dv:f:0.0860	rl:i:0
LongReads_3	6823	6488	6747	+	7316	1680	1389	1674	110	285	56	tp:A:P	cm:i:13	s1:i:105	s2:i:73	dv:f:0.0842	rl:i:0
```
and here the command

`java -jar LRScaf-1.1.8r2.jar -x scafconf.xml`

```
<scaffold>
	<input>
		<contig>Assembly.fasta</contig>
		<mm>./aln2.mm</mm>
	</input>
	<output>./out_LRSscaf</output>
	<paras>
		<min_contig_length>200</min_contig_length>
		<identity>0.3</identity>
		<min_overlap_length>10</min_overlap_length>
		<min_overlap_ratio>0.6</min_overlap_ratio>
		<max_overhang_length>10000</max_overhang_length>
		<max_overhang_ratio>0.8</max_overhang_ratio>
		<max_end_length>5000</max_end_length>
		<max_end_ratio>0.8</max_end_ratio>
		<min_supported_links>1</min_supported_links>
		<!--<tips_length>100</tips_length>-->
		<ratio>0.2</ratio>
		<repeat_mask>true</repeat_mask>
		<iqr_time>1.5</iqr_time>
		<mmcm>8</mmcm>
		<process>8</process>
	</paras>
</scaffold>
```

**Comment by shingocat** [comment]
Hi AndreaGuarracino,

Try to use the LRScaf-1.1.8r3.jar and feedback to me.
Thanks.

**Comment by AndreaGuarracino** [comment]
Hi @shingocat, thank you for you work. Using the same **aln2.mm** file, I get these error messages:

```
2020-04-18 13:51:55 [ INFO ]  Parsing the xml configure, all the other parameters set by command line will dismissed!
2020-04-18 13:51:55 [ WARN ]  The identity is setted to 0.3.
2020-04-18 13:51:55 [ WARN ]  The identity for Minimap mapper should be not large than 0.3!
2020-04-18 13:51:55 [ INFO ]  Launching...
2020-04-18 13:51:55 [ INFO ]  Build output folder successfully!
2020-04-18 13:51:55 [ INFO ]  Building output folder, erase time: 0 ms
2020-04-18 13:51:55 [ INFO ]  Reading contigs, erase times: 72 ms
2020-04-18 13:51:55 [ DEBUG ]  MRecord [qName=LongReads_1, qLength=7076, qStart=136, qEnd=6701, qStrand=null, tName=754, tLength=10397, tStart=32, tEnd=6857, tStrand=+, identity=0.4967]
java.lang.NullPointerException
	at agis.ps.util.MRecordValidator.validate(MRecordValidator.java:245)
	at agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:124)
	at agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:59)
	at agis.ps.Scaffolder.buildLinks(Scaffolder.java:118)
	at agis.ps.Scaffolder.scaffolding(Scaffolder.java:74)
	at agis.ps.Main.main(Main.java:58)
2020-04-18 13:51:55 [ ERROR ]  agis.ps.file.MMReader	On lines: 1	java.lang.IllegalArgumentException: The contig ID, 754, in alignment file is not in your input draft assembly file! Please checking the contig ID.
2020-04-18 13:51:55 [ ERROR ]  agis.ps.file.MMReader	On lines: 1	The contig ID, 754, in alignment file is not in your input draft assembly file! Please checking the contig ID.
java.lang.IllegalArgumentException: The contig ID, 754, in alignment file is not in your input draft assembly file! Please checking the contig ID.
	at agis.ps.util.MRecordValidator.validate(MRecordValidator.java:253)
	at agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:124)
	at agis.ps.file.AlignmentFileReader.read(AlignmentFileReader.java:59)
	at agis.ps.Scaffolder.buildLinks(Scaffolder.java:118)
	at agis.ps.Scaffolder.scaffolding(Scaffolder.java:74)
	at agis.ps.Main.main(Main.java:58)
2020-04-18 13:51:55 [ INFO ]  Valid Aligned Records: 0
2020-04-18 13:51:55 [ INFO ]  Reading Aligned Records, erase time: 21 ms
2020-04-18 13:51:55 [ INFO ]  Repeat count: 0
2020-04-18 13:51:55 [ INFO ]  Finding repeat, erase time: 0 ms
2020-04-18 13:51:55 [ INFO ]  Valid Links Acount: 0
2020-04-18 13:51:55 [ INFO ]  Building Link, erase time : 96 ms
java.lang.IllegalArgumentException: PathBuilder ： The Edges could not be empty!
	at agis.ps.util.PathBuilder.buildPath(PathBuilder.java:70)
	at agis.ps.Scaffolder.buildPaths(Scaffolder.java:144)
	at agis.ps.Scaffolder.scaffolding(Scaffolder.java:76)
	at agis.ps.Main.main(Main.java:58)
2020-04-18 13:51:55 [ ERROR ]  PathBuilder ： The Edges could not be empty!
2020-04-18 13:51:55 [ INFO ]  Ending...
2020-04-18 13:51:55 [ INFO ]  Scaffolding erase time: 0 s.
```

**Comment by shingocat** [comment]
Hi AndreaGuarracino,

LRScaf will check contig id between PAF and draft assembly file.
This excepiton means that your draft assembly file does not have the contig 754. 
Pls check your Assembly.fasta file.

the contig 754 in assembly.fasta looks like:
\>754
atcg....atgc

**Comment by AndreaGuarracino** [comment]
Ops, I am sorry, you're right, I've used an old assembly, but only in the last test, so please don't consider the last error message. The latest version seems to work (I get a scaffolds.fasta), so I can finally start using your tool to get familiar with it, thank you for your hard work. I hope I won't disturb you anymore!

**Comment by pdroslva84** [comment]
Hi @shingocat ,

I just used the 1.1.9 jar and it worked without problems, thank you very much for your work.
Cheers!
